
#############################
# Project-specific configuration
#############################

# Allowable redirection
BSG_DIR          ?= $(TOP)
BSG_WORK_DIR     ?= $(BSG_DIR)/work
BSG_INSTALL_DIR  ?= $(BSG_DIR)/install

# toplevel subdirectories
BSG_PATCH_DIR     = $(BSG_DIR)/patches
BSG_MK_DIR        = $(BSG_DIR)/mk

# toplevel submodules
OPENSTA_DIR       = $(BSG_DIR)/OpenSTA
SURELOG_DIR       = $(BSG_DIR)/Surelog
BASEJUMP_STL_DIR  = $(BSG_DIR)/basejump_stl
BSG_PEARLS_DIR    = $(BSG_DIR)/bsg_pearls
IVERILOG_DIR      = $(BSG_DIR)/iverilog
MORTY_DIR         = $(BSG_DIR)/morty
SURFER_DIR        = $(BSG_DIR)/surfer
SVASE_DIR         = $(BSG_DIR)/svase
VERILATOR_DIR     = $(BSG_DIR)/verilator
YOSYS_DIR         = $(BSG_DIR)/yosys
F4PGA_DIR         = $(BSG_DIR)/yosys-f4pga-plugins
YSLANG_DIR        = $(BSG_DIR)/yosys-slang
SV2V_DIR          = $(BSG_DIR)/sv2v

# installation subdirectories
BSG_BIN_DIR       = $(BSG_INSTALL_DIR)/bin
BSG_LIB_DIR       = $(BSG_INSTALL_DIR)/lib
BSG_INCLUDE_DIR   = $(BSG_INSTALL_DIR)/include
BSG_SHARE_DIR     = $(BSG_INSTALL_DIR)/share
BSG_TOUCH_DIR     = $(BSG_INSTALL_DIR)/touchfiles

# Add tool binaries to the PATH
export PATH := $(BSG_BIN_DIR):$(PATH)

export CARGO ?= cargo
export FALSE ?= false
export TRUE  ?= true

#############################
# Hooks
#############################

## Probably don't need to change, but here's the hook anyway
HOOK_REPO_NAME = oss-cad-playground
## All local directories to create during checkout
HOOK_CHECKOUT_DIRS = \
        $(BSG_WORK_DIR) \
        $(BSG_INSTALL_DIR)
## Long checkouts to disable
HOOK_DISABLE_SUBMODULES = \
        $(YSLANG_DIR)@tests/third_party/croc \
        $(YSLANG_DIR)@tests/third_party/yosys

